import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import AuthProvider from "@/providers/AuthProvider";
import { Toaster } from "react-hot-toast";
import LocationProvider from "@/providers/LocationProvider";
import Navbar from "@/components/ui/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Grocery App",
  description: "Generated by grocery app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LocationProvider>
          <AuthProvider>
            <Toaster />
            <ToastContainer />
            <ToastContainer
              containerId="cart"
              position="top-center"
              toastClassName="toast-cart"
            />
            <ToastContainer
              containerId="order"
              position="top-center"
              toastClassName="toast-order"
            />

            <Navbar />
            {children}
          </AuthProvider>
        </LocationProvider>
      </body>
    </html>
  );
}
